/**
 * Programmed by: Donaldo Cruz with help from the book, Data Structures & Other Objects Using JAVA, by Michael Main.
 * Stack: a data structure of ordered items such that items can be inserted and removed only at one end (called the top).
 */

public class Stack<E> {

    /*Instance variables*/

    /**
     * Default Constructor
     */
    public Stack() {

    }

    /**
     * This method determines if this stack is empty.
     * @return True if this stack is empty.
     */
    public boolean isEmpty() {

    }

    /**
     * This method gets the top element of the stack without removing the item.
     * @return The element at the top of the stack.
     */
    public E peek() {

    }

    /**
     * This method gets the top element of the stack, and removes it from the stack.
     * @return The element at the top of the stack.
     */
    public E pop() {

    }

    /**
     * This method add an element to the top of the stack.
     * @param element The element to be added to the top of the stack.
     */
    public void push(E element) {

    }

    /**
     * This method determines the number of elements in this stack.
     * @return The number of elements in this stack.
     */
    public int size() {

    }
}